# Generated by Django 4.1 on 2023-03-12 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_category_women_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatetags',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='university.category'),
        ),
    ]
